project:
  type: website
  output-dir: "docs"
  render: 
    - "*.qmd"
    - "!_*.qmd"

website:
  title: "Hello Data Science"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: blog_listing.qmd
        text: Blog
    right:
      - icon: git
        href: https://github.com/hello-data-science/hds
        aria-label: github_gitlab
  repo-url: https://github.com/hello-data-science/hds
  repo-actions: [edit, issue]
  repo-branch: main
  reader-mode: true

format:
  html:
    mermaid:
      theme: default
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    code-fold: true
    code-link: true
    code-tools:
      source: repo
      toggle: true
      caption: Code
  live-html:
    mermaid:
      theme: default
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    code-fold: true
    code-link: true
    code-tools:
      source: repo
      toggle: true
      caption: Code

editor: source


